import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error('DATABASE_URL is not set');
}

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

const candidates = [
  // ===== FULL STACK =====
  { name: 'Arjun Patel', role: 'Senior Full Stack Developer', skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS', 'GraphQL'], experience: 7, location: 'Bangalore, India', domain: 'FinTech', company: 'Razorpay', education: 'IIT Bombay - B.Tech CS', skillScore: 92, roleScore: 88, experienceScore: 85, domainScore: 80, trajectoryScore: 90, referralScore: 60, riskScore: 10, reasoning: ['Strong React/Node.js stack — 5+ years production', 'FinTech domain expertise at Razorpay', 'Consistent career growth from Mid to Senior in 3 years', 'IIT Bombay alumnus with strong foundation'] },
  { name: 'Vikram Singh', role: 'Full Stack Developer', skills: ['React', 'Node.js', 'MongoDB', 'Docker', 'Redis', 'Socket.io'], experience: 3, location: 'Pune, India', domain: 'EdTech', company: 'Byju\'s', education: 'VIT - B.Tech CS', skillScore: 78, roleScore: 74, experienceScore: 60, domainScore: 65, trajectoryScore: 75, referralScore: 20, riskScore: 20, reasoning: ['React/Node.js full-stack with production experience', 'EdTech experience with real-time features', 'Fast learner — shipped 3 features in first year', 'Higher risk due to company instability'] },
  { name: 'Ravi Kumar', role: 'Full Stack Engineer', skills: ['React', 'Python', 'Django', 'PostgreSQL', 'AWS', 'Docker'], experience: 5, location: 'Chennai, India', domain: 'HealthTech', company: 'Practo', education: 'Anna University - B.Tech IT', skillScore: 85, roleScore: 82, experienceScore: 75, domainScore: 78, trajectoryScore: 80, referralScore: 45, riskScore: 12, reasoning: ['Strong React + Django stack', 'HealthTech domain at Practo', 'AWS for HIPAA-compliant systems', 'Solid university background'] },
  { name: 'Nina Kowalski', role: 'Full Stack Developer', skills: ['Vue.js', 'Node.js', 'TypeScript', 'MySQL', 'GCP', 'Terraform'], experience: 4, location: 'Warsaw, Poland', domain: 'E-commerce', company: 'Allegro', education: 'Warsaw University - MS CS', skillScore: 80, roleScore: 78, experienceScore: 68, domainScore: 72, trajectoryScore: 82, referralScore: 35, riskScore: 10, reasoning: ['Vue.js with TypeScript', 'E-commerce scale at Allegro', 'GCP and Terraform skills', 'Strong academic background'] },
  { name: 'Carlos Rodriguez', role: 'Senior Full Stack Engineer', skills: ['React', 'Go', 'PostgreSQL', 'Kubernetes', 'gRPC', 'Redis'], experience: 8, location: 'Mexico City, Mexico', domain: 'FinTech', company: 'Clip', education: 'UNAM - MS Software Engineering', skillScore: 88, roleScore: 86, experienceScore: 85, domainScore: 82, trajectoryScore: 84, referralScore: 50, riskScore: 8, reasoning: ['React + Go high-performance stack', 'FinTech payments at Clip', 'Kubernetes and gRPC microservices', 'Senior with 8 years trajectory'] },
  { name: 'Grace Okafor', role: 'Full Stack Developer', skills: ['React', 'Node.js', 'MongoDB', 'Express', 'AWS', 'TypeScript'], experience: 3, location: 'Lagos, Nigeria', domain: 'FinTech', company: 'Flutterwave', education: 'University of Lagos - BS CS', skillScore: 78, roleScore: 76, experienceScore: 60, domainScore: 78, trajectoryScore: 80, referralScore: 25, riskScore: 14, reasoning: ['MERN stack at Flutterwave', 'African FinTech payments experience', 'AWS cloud deployments', 'Rising talent in African tech'] },

  // ===== FRONTEND =====
  { name: 'Priya Sharma', role: 'Frontend Engineer', skills: ['React', 'TypeScript', 'Next.js', 'CSS', 'Figma', 'Testing'], experience: 4, location: 'Mumbai, India', domain: 'E-commerce', company: 'Flipkart', education: 'BITS Pilani - B.Tech', skillScore: 88, roleScore: 82, experienceScore: 70, domainScore: 75, trajectoryScore: 85, referralScore: 40, riskScore: 15, reasoning: ['Expert React/Next.js proficiency', 'E-commerce scale at Flipkart', 'Strong design sensibility with Figma', 'Promoted twice in 4 years'] },
  { name: 'Alex Chen', role: 'Senior Frontend Developer', skills: ['React', 'TypeScript', 'GraphQL', 'Storybook', 'Jest', 'Accessibility'], experience: 6, location: 'Toronto, Canada', domain: 'SaaS', company: 'Shopify', education: 'University of Toronto - BS CS', skillScore: 90, roleScore: 85, experienceScore: 80, domainScore: 78, trajectoryScore: 88, referralScore: 55, riskScore: 8, reasoning: ['React with accessibility focus at Shopify', 'Design system builder with Storybook', 'Strong testing culture', 'UofT CS graduate'] },
  { name: 'Yuki Tanaka', role: 'Frontend Engineer', skills: ['React', 'Vue.js', 'TypeScript', 'Tailwind', 'Vite', 'WebGL'], experience: 3, location: 'Tokyo, Japan', domain: 'Gaming', company: 'Bandai Namco', education: 'Waseda University - BS CS', skillScore: 82, roleScore: 76, experienceScore: 58, domainScore: 70, trajectoryScore: 80, referralScore: 25, riskScore: 12, reasoning: ['Multi-framework frontend', 'WebGL for gaming UIs', 'Vite and Tailwind for rapid dev', 'Japanese gaming industry'] },
  { name: 'Aditi Rao', role: 'Frontend Engineer', skills: ['React', 'TypeScript', 'Redux', 'GraphQL', 'Jest', 'Webpack'], experience: 4, location: 'Bangalore, India', domain: 'FinTech', company: 'Cred', education: 'PES University - B.Tech', skillScore: 84, roleScore: 80, experienceScore: 68, domainScore: 78, trajectoryScore: 82, referralScore: 35, riskScore: 10, reasoning: ['React/Redux at Cred', 'FinTech premium UI', 'GraphQL API integration', 'Growing frontend career'] },

  // ===== BACKEND =====
  { name: 'Michael Torres', role: 'Backend Engineer', skills: ['Java', 'Spring Boot', 'Microservices', 'PostgreSQL', 'Redis', 'RabbitMQ'], experience: 6, location: 'New York, USA', domain: 'Banking', company: 'Goldman Sachs', education: 'Columbia - BS CS', skillScore: 86, roleScore: 84, experienceScore: 80, domainScore: 88, trajectoryScore: 78, referralScore: 70, riskScore: 10, reasoning: ['Enterprise Java at Goldman Sachs', 'Banking domain compliance', 'High-throughput microservices', 'VP-level referral'] },
  { name: 'Olga Petrova', role: 'Senior Backend Developer', skills: ['Go', 'PostgreSQL', 'Kafka', 'gRPC', 'Docker', 'Prometheus'], experience: 7, location: 'Berlin, Germany', domain: 'FinTech', company: 'N26', education: 'Moscow State University - MS CS', skillScore: 87, roleScore: 84, experienceScore: 82, domainScore: 85, trajectoryScore: 80, referralScore: 45, riskScore: 8, reasoning: ['Go backend for high-performance at N26', 'Event-driven FinTech architecture', 'Kafka and gRPC real-time processing', 'Prometheus monitoring at scale'] },
  { name: 'Ahmed Hassan', role: 'Backend Engineer', skills: ['Python', 'FastAPI', 'PostgreSQL', 'Celery', 'Docker', 'AWS'], experience: 4, location: 'Cairo, Egypt', domain: 'Logistics', company: 'Swvl', education: 'Cairo University - BS CS', skillScore: 80, roleScore: 78, experienceScore: 68, domainScore: 72, trajectoryScore: 82, referralScore: 30, riskScore: 15, reasoning: ['Python/FastAPI modern APIs', 'Logistics domain async processing', 'AWS deployment experience', 'Growing startup experience'] },
  { name: 'Deepak Menon', role: 'Senior Backend Engineer', skills: ['Node.js', 'TypeScript', 'PostgreSQL', 'Redis', 'Elasticsearch', 'AWS'], experience: 6, location: 'Bangalore, India', domain: 'SaaS', company: 'Zoho', education: 'NIT Surathkal - B.Tech', skillScore: 84, roleScore: 82, experienceScore: 78, domainScore: 80, trajectoryScore: 82, referralScore: 50, riskScore: 10, reasoning: ['Node.js/TS backend at scale', 'SaaS product experience at Zoho', 'Elasticsearch infrastructure', 'NIT graduate'] },
  { name: 'Ivan Popov', role: 'Backend Developer', skills: ['Python', 'Django', 'PostgreSQL', 'Celery', 'Docker', 'Linux'], experience: 5, location: 'Moscow, Russia', domain: 'E-commerce', company: 'Yandex Market', education: 'MIPT - BS CS', skillScore: 82, roleScore: 78, experienceScore: 74, domainScore: 76, trajectoryScore: 78, referralScore: 30, riskScore: 12, reasoning: ['Django backend at Yandex scale', 'Async with Celery', 'MIPT CS education', 'E-commerce catalog expertise'] },
  { name: 'Leo Zhang', role: 'Backend Engineer', skills: ['Rust', 'C++', 'PostgreSQL', 'Redis', 'System Design', 'Linux'], experience: 7, location: 'Shanghai, China', domain: 'Gaming', company: 'miHoYo', education: 'Fudan University - BS CS', skillScore: 88, roleScore: 82, experienceScore: 80, domainScore: 78, trajectoryScore: 84, referralScore: 40, riskScore: 10, reasoning: ['Rust/C++ high-performance at miHoYo', 'Genshin Impact server infra', 'Low-latency system design', 'Fudan CS foundation'] },

  // ===== AI/ML =====
  { name: 'Sarah Chen', role: 'Staff Engineer', skills: ['Python', 'Machine Learning', 'TensorFlow', 'Kubernetes', 'Go', 'System Design'], experience: 10, location: 'San Francisco, USA', domain: 'AI/ML', company: 'Google', education: 'Stanford - MS Computer Science', skillScore: 95, roleScore: 92, experienceScore: 90, domainScore: 95, trajectoryScore: 95, referralScore: 80, riskScore: 5, reasoning: ['Deep ML with TensorFlow at Google', 'Staff-level AI leadership', 'Stanford MS with NLP research', 'Strong internal referral'] },
  { name: 'Rahul Verma', role: 'AI/ML Engineer', skills: ['Python', 'PyTorch', 'NLP', 'LLMs', 'MLOps', 'FastAPI'], experience: 4, location: 'Delhi, India', domain: 'AI/ML', company: 'Ola', education: 'IISc Bangalore - MTech AI', skillScore: 90, roleScore: 82, experienceScore: 68, domainScore: 90, trajectoryScore: 92, referralScore: 40, riskScore: 12, reasoning: ['LLM and NLP expertise', 'IISc MTech in AI', 'ML recommendation system for 50M+ users', 'Intern to lead in 3 years'] },
  { name: 'Dr. Mei Lin', role: 'Research Scientist', skills: ['Python', 'PyTorch', 'Computer Vision', 'Transformers', 'CUDA', 'Research'], experience: 8, location: 'Beijing, China', domain: 'AI/ML', company: 'ByteDance', education: 'Tsinghua University - PhD CS', skillScore: 94, roleScore: 88, experienceScore: 85, domainScore: 92, trajectoryScore: 90, referralScore: 45, riskScore: 8, reasoning: ['PhD computer vision at ByteDance', 'CUDA optimization for production ML', '15+ papers in top venues', 'Tsinghua PhD'] },
  { name: 'Marcus Wright', role: 'ML Engineer', skills: ['Python', 'TensorFlow', 'Spark', 'Docker', 'MLflow', 'SQL'], experience: 5, location: 'Austin, USA', domain: 'Healthcare', company: 'Tempus', education: 'Georgia Tech - MS ML', skillScore: 84, roleScore: 80, experienceScore: 75, domainScore: 78, trajectoryScore: 82, referralScore: 55, riskScore: 10, reasoning: ['ML in healthcare at Tempus', 'MLOps pipeline expertise', 'Spark for large-scale processing', 'Georgia Tech ML'] },
  { name: 'Shreya Iyer', role: 'AI Engineer', skills: ['Python', 'LLMs', 'RAG', 'LangChain', 'Vector DBs', 'FastAPI'], experience: 3, location: 'Hyderabad, India', domain: 'AI/ML', company: 'Fractal Analytics', education: 'IIIT Hyderabad - MTech AI', skillScore: 86, roleScore: 78, experienceScore: 62, domainScore: 88, trajectoryScore: 85, referralScore: 30, riskScore: 14, reasoning: ['LLM and RAG pipeline expertise', 'Vector DB for semantic search', 'IIIT Hyderabad AI', 'Fast-growing GenAI skills'] },
  { name: 'Sneha Reddy', role: 'ML Engineer', skills: ['Python', 'TensorFlow', 'Keras', 'Docker', 'FastAPI', 'SQL'], experience: 3, location: 'Hyderabad, India', domain: 'Healthcare', company: 'Apollo 247', education: 'IIIT Hyderabad - MTech', skillScore: 80, roleScore: 76, experienceScore: 62, domainScore: 76, trajectoryScore: 80, referralScore: 25, riskScore: 14, reasoning: ['ML for healthcare diagnostics', 'TensorFlow/Keras deployment', 'Patient data handling', 'IIIT Hyderabad AI'] },
  { name: 'Pablo Garcia', role: 'Data Scientist', skills: ['Python', 'R', 'Machine Learning', 'SQL', 'Tableau', 'Statistics'], experience: 5, location: 'Madrid, Spain', domain: 'Banking', company: 'BBVA', education: 'Universidad Politécnica - MS Data Science', skillScore: 82, roleScore: 80, experienceScore: 74, domainScore: 80, trajectoryScore: 78, referralScore: 40, riskScore: 10, reasoning: ['Data science in European banking', 'Credit risk ML models', 'R + Python bilingual', 'Strong statistics foundation'] },

  // ===== DEVOPS / CLOUD =====
  { name: 'James Wilson', role: 'DevOps Lead', skills: ['AWS', 'Terraform', 'Docker', 'Kubernetes', 'CI/CD', 'Python'], experience: 8, location: 'London, UK', domain: 'Healthcare', company: 'DeepMind Health', education: 'Oxford - MEng', skillScore: 85, roleScore: 80, experienceScore: 88, domainScore: 70, trajectoryScore: 82, referralScore: 50, riskScore: 12, reasoning: ['AWS/K8s at scale', 'Healthcare compliance (HIPAA, GDPR)', '80% faster deploys', 'Manages team of 6'] },
  { name: 'Aisha Khan', role: 'Cloud Architect', skills: ['AWS', 'Azure', 'Terraform', 'Kubernetes', 'Serverless', 'Cost Optimization'], experience: 11, location: 'Dubai, UAE', domain: 'Government', company: 'Accenture', education: 'LUMS - BS CS', skillScore: 88, roleScore: 88, experienceScore: 92, domainScore: 75, trajectoryScore: 84, referralScore: 55, riskScore: 8, reasoning: ['Multi-cloud enterprise architecture', 'Government security-first design', 'Saved $2M+ in cloud spend', 'Strong leadership'] },
  { name: 'Sven Eriksson', role: 'Site Reliability Engineer', skills: ['Kubernetes', 'Go', 'Prometheus', 'Grafana', 'Terraform', 'Linux'], experience: 6, location: 'Stockholm, Sweden', domain: 'FinTech', company: 'Klarna', education: 'KTH - MS CS', skillScore: 84, roleScore: 82, experienceScore: 78, domainScore: 80, trajectoryScore: 80, referralScore: 40, riskScore: 10, reasoning: ['SRE at Klarna scale', 'Go-based observability tooling', 'Prometheus/Grafana monitoring', 'KTH-trained engineer'] },
  { name: 'Fatima Al-Said', role: 'DevOps Engineer', skills: ['AWS', 'Docker', 'Jenkins', 'Ansible', 'Python', 'Linux'], experience: 4, location: 'Riyadh, Saudi Arabia', domain: 'E-commerce', company: 'Noon', education: 'KFUPM - BS CS', skillScore: 78, roleScore: 76, experienceScore: 68, domainScore: 72, trajectoryScore: 80, referralScore: 35, riskScore: 10, reasoning: ['AWS for Middle East e-commerce', 'Jenkins CI/CD automation', 'Growing DevOps at Noon', 'Top KFUPM graduate'] },
  { name: 'Tanya Gupta', role: 'Platform Engineer', skills: ['Kubernetes', 'Go', 'Terraform', 'ArgoCD', 'Istio', 'Linux'], experience: 5, location: 'Delhi, India', domain: 'E-commerce', company: 'Meesho', education: 'DTU - B.Tech', skillScore: 84, roleScore: 80, experienceScore: 74, domainScore: 72, trajectoryScore: 82, referralScore: 35, riskScore: 12, reasoning: ['Platform engineering at Meesho scale', 'K8s + ArgoCD GitOps', 'Istio service mesh', 'DTU with DevOps focus'] },

  // ===== DATA ENGINEERING =====
  { name: 'Kavitha Reddy', role: 'Data Engineer', skills: ['Python', 'Spark', 'Airflow', 'SQL', 'Kafka', 'dbt'], experience: 5, location: 'Hyderabad, India', domain: 'Analytics', company: 'Myntra', education: 'NIT Warangal - B.Tech', skillScore: 82, roleScore: 78, experienceScore: 75, domainScore: 72, trajectoryScore: 80, referralScore: 30, riskScore: 8, reasoning: ['Spark and Airflow pipelines', '10M+ events/day analytics', 'Strong SQL with dbt', 'Open-source contributor'] },
  { name: 'Jake Thompson', role: 'Senior Data Engineer', skills: ['Python', 'Spark', 'Snowflake', 'dbt', 'Airflow', 'AWS'], experience: 7, location: 'Chicago, USA', domain: 'FinTech', company: 'Stripe', education: 'UIUC - BS CS', skillScore: 86, roleScore: 84, experienceScore: 82, domainScore: 85, trajectoryScore: 82, referralScore: 60, riskScore: 8, reasoning: ['Data platform at Stripe', 'Snowflake + dbt modern stack', 'Financial data compliance', 'UIUC CS'] },
  { name: 'Priti Deshmukh', role: 'Data Engineer', skills: ['Python', 'SQL', 'Databricks', 'Delta Lake', 'Azure', 'PySpark'], experience: 4, location: 'Pune, India', domain: 'Insurance', company: 'Tata AIG', education: 'COEP - B.Tech', skillScore: 78, roleScore: 76, experienceScore: 68, domainScore: 70, trajectoryScore: 78, referralScore: 25, riskScore: 12, reasoning: ['Databricks/Delta Lake expertise', 'Insurance data pipelines', 'Azure cloud skills', 'Growing data career'] },
  { name: 'Daniel Müller', role: 'Data Platform Engineer', skills: ['Spark', 'Kafka', 'Scala', 'Airflow', 'AWS', 'Terraform'], experience: 6, location: 'Zurich, Switzerland', domain: 'Banking', company: 'UBS', education: 'ETH Zurich - MS CS', skillScore: 86, roleScore: 82, experienceScore: 78, domainScore: 84, trajectoryScore: 80, referralScore: 50, riskScore: 8, reasoning: ['Data platform at UBS', 'Spark + Kafka real-time', 'ETH Zurich world-class CS', 'Swiss banking compliance'] },

  // ===== MOBILE =====
  { name: 'David Kim', role: 'Mobile Developer', skills: ['React Native', 'Swift', 'Kotlin', 'Firebase', 'GraphQL', 'TypeScript'], experience: 6, location: 'Seoul, South Korea', domain: 'Social Media', company: 'LINE Corporation', education: 'KAIST - BS CS', skillScore: 84, roleScore: 80, experienceScore: 78, domainScore: 76, trajectoryScore: 82, referralScore: 35, riskScore: 15, reasoning: ['Cross-platform mobile at LINE', '200M+ user base', 'TypeScript for code-sharing', 'KAIST CS'] },
  { name: 'Maria Santos', role: 'iOS Developer', skills: ['Swift', 'SwiftUI', 'Core Data', 'Firebase', 'CI/CD', 'Testing'], experience: 5, location: 'São Paulo, Brazil', domain: 'FinTech', company: 'Nubank', education: 'USP - BS CS', skillScore: 85, roleScore: 82, experienceScore: 75, domainScore: 80, trajectoryScore: 84, referralScore: 45, riskScore: 8, reasoning: ['SwiftUI at Nubank', 'FinTech mobile payments', 'Strong testing/CI/CD culture', 'Top Brazilian CS university'] },
  { name: 'Ankit Joshi', role: 'Mobile Engineer', skills: ['Flutter', 'Dart', 'Firebase', 'REST APIs', 'SQLite', 'GetX'], experience: 3, location: 'Jaipur, India', domain: 'EdTech', company: 'Unacademy', education: 'IIIT Jaipur - B.Tech', skillScore: 76, roleScore: 74, experienceScore: 58, domainScore: 68, trajectoryScore: 78, referralScore: 20, riskScore: 18, reasoning: ['Flutter cross-platform', 'EdTech mobile experience', 'Multiple published apps', 'Higher risk — EdTech market'] },

  // ===== SECURITY =====
  { name: 'Lisa Anderson', role: 'Security Engineer', skills: ['Penetration Testing', 'SIEM', 'Python', 'Cloud Security', 'ISO 27001', 'SOC 2'], experience: 9, location: 'Austin, USA', domain: 'Cybersecurity', company: 'CrowdStrike', education: 'Georgia Tech - MS InfoSec', skillScore: 88, roleScore: 86, experienceScore: 90, domainScore: 92, trajectoryScore: 80, referralScore: 60, riskScore: 5, reasoning: ['Deep cybersecurity at CrowdStrike', 'ISO 27001, SOC 2 compliance', 'Pen testing + strategic architecture', 'Georgia Tech InfoSec'] },
  { name: 'Karthik Nair', role: 'Application Security Engineer', skills: ['OWASP', 'Python', 'Burp Suite', 'AWS Security', 'SAST/DAST', 'Code Review'], experience: 5, location: 'Bangalore, India', domain: 'FinTech', company: 'Paytm', education: 'NIT Calicut - B.Tech', skillScore: 82, roleScore: 80, experienceScore: 75, domainScore: 80, trajectoryScore: 78, referralScore: 40, riskScore: 10, reasoning: ['AppSec with OWASP at Paytm', 'FinTech security', 'SAST/DAST pipeline', 'Strong code review'] },

  // ===== DESIGN =====
  { name: 'Ananya Gupta', role: 'Product Designer', skills: ['Figma', 'UI/UX', 'Design Systems', 'Prototyping', 'User Research', 'HTML/CSS'], experience: 5, location: 'Bangalore, India', domain: 'SaaS', company: 'Freshworks', education: 'NID Ahmedabad - MDes', skillScore: 90, roleScore: 85, experienceScore: 78, domainScore: 82, trajectoryScore: 88, referralScore: 45, riskScore: 8, reasoning: ['NID systematic design thinking', 'Design system across 5 products', '35% conversion improvement', 'B2B SaaS design excellence'] },
  { name: 'Emily Park', role: 'UX Researcher', skills: ['User Research', 'Figma', 'Usability Testing', 'Data Analysis', 'Surveys', 'A/B Testing'], experience: 4, location: 'San Francisco, USA', domain: 'SaaS', company: 'Notion', education: 'Carnegie Mellon - MS HCI', skillScore: 84, roleScore: 80, experienceScore: 70, domainScore: 78, trajectoryScore: 82, referralScore: 50, riskScore: 8, reasoning: ['UX Research at Notion', 'CMU HCI degree', 'Quantitative + qualitative methods', 'A/B testing frameworks'] },

  // ===== QA =====
  { name: 'Sophie Martin', role: 'QA Lead', skills: ['Selenium', 'Cypress', 'API Testing', 'Performance Testing', 'Python', 'CI/CD'], experience: 7, location: 'Berlin, Germany', domain: 'Automotive', company: 'BMW Digital', education: 'TU Munich - MS Software Engineering', skillScore: 82, roleScore: 80, experienceScore: 82, domainScore: 70, trajectoryScore: 76, referralScore: 50, riskScore: 10, reasoning: ['UI, API, performance QA', '60% defect rate reduction at BMW', 'Selenium + Cypress automation', 'TU Munich credentials'] },
  { name: 'Rajesh Pillai', role: 'SDET', skills: ['Java', 'Selenium', 'REST Assured', 'TestNG', 'Jenkins', 'Docker'], experience: 5, location: 'Kochi, India', domain: 'Banking', company: 'Federal Bank', education: 'NIT Trichy - B.Tech', skillScore: 80, roleScore: 78, experienceScore: 74, domainScore: 75, trajectoryScore: 76, referralScore: 35, riskScore: 10, reasoning: ['Java test automation', 'Banking domain testing', 'REST API testing', 'CI/CD integration'] },

  // ===== BLOCKCHAIN =====
  { name: 'Tom Nakamura', role: 'Blockchain Developer', skills: ['Solidity', 'Rust', 'Web3.js', 'Smart Contracts', 'DeFi', 'TypeScript'], experience: 4, location: 'Tokyo, Japan', domain: 'Web3', company: 'Astar Network', education: 'University of Tokyo - MS CS', skillScore: 86, roleScore: 78, experienceScore: 65, domainScore: 88, trajectoryScore: 85, referralScore: 30, riskScore: 18, reasoning: ['Solidity/Rust mainnet contracts', 'DeFi protocol development', 'University of Tokyo foundation', 'Web3 market volatility risk'] },

  // ===== MANAGEMENT =====
  { name: 'Emma Johnson', role: 'Engineering Manager', skills: ['People Management', 'Agile', 'System Design', 'Java', 'Stakeholder Management', 'OKRs'], experience: 12, location: 'Seattle, USA', domain: 'Cloud Computing', company: 'Amazon Web Services', education: 'MIT - BS CS', skillScore: 78, roleScore: 90, experienceScore: 95, domainScore: 85, trajectoryScore: 88, referralScore: 75, riskScore: 8, reasoning: ['Engineering leadership at AWS 15+ engineers', 'Large-scale cloud infrastructure', 'MIT with technical depth', 'Director-level referral'] },
  { name: 'Suresh Krishnan', role: 'VP of Engineering', skills: ['Leadership', 'Strategy', 'Agile', 'Architecture', 'Budgeting', 'Hiring'], experience: 15, location: 'Bangalore, India', domain: 'SaaS', company: 'InMobi', education: 'IIT Madras - B.Tech', skillScore: 72, roleScore: 92, experienceScore: 95, domainScore: 82, trajectoryScore: 90, referralScore: 70, riskScore: 5, reasoning: ['VP-level SaaS at InMobi', 'Org from 20 to 100+ engineers', 'IIT Madras CTO-track', 'Strong industry network'] },
  { name: 'Neha Agarwal', role: 'Product Manager', skills: ['Product Strategy', 'Analytics', 'SQL', 'A/B Testing', 'Figma', 'Agile'], experience: 6, location: 'Bangalore, India', domain: 'FinTech', company: 'PhonePe', education: 'ISB Hyderabad - MBA', skillScore: 75, roleScore: 84, experienceScore: 78, domainScore: 82, trajectoryScore: 86, referralScore: 50, riskScore: 10, reasoning: ['Product at PhonePe scale', 'Data-driven with SQL + analytics', 'ISB MBA product focus', 'FinTech payments domain'] },

  // ===== OTHER ROLES =====
  { name: 'Hannah Mueller', role: 'Technical Writer', skills: ['Documentation', 'Markdown', 'API Docs', 'Swagger', 'Git', 'HTML'], experience: 4, location: 'Munich, Germany', domain: 'SaaS', company: 'Celonis', education: 'LMU Munich - MA English', skillScore: 78, roleScore: 76, experienceScore: 68, domainScore: 72, trajectoryScore: 75, referralScore: 30, riskScore: 8, reasoning: ['Technical documentation expertise', 'API docs with Swagger', 'SaaS docs at Celonis', 'LMU Munich graduate'] },
  { name: 'Chris O\'Brien', role: 'Solutions Architect', skills: ['AWS', 'System Design', 'Microservices', 'Docker', 'Client Relations', 'SQL'], experience: 9, location: 'Dublin, Ireland', domain: 'Cloud Computing', company: 'AWS', education: 'Trinity College Dublin - BS Eng', skillScore: 82, roleScore: 86, experienceScore: 88, domainScore: 85, trajectoryScore: 80, referralScore: 55, riskScore: 8, reasoning: ['AWS Solutions Architect', 'Enterprise microservices', 'Trinity College engineering', 'Strong pre-sales technical'] },
];

async function main() {
  console.log('🌱 Seeding candidates...');
  
  // Clear existing candidates
  await prisma.candidate.deleteMany();
  
  let count = 0;
  for (const c of candidates) {
    await prisma.candidate.create({
      data: {
        name: c.name,
        role: c.role,
        skills: c.skills,
        experience: c.experience,
        location: c.location,
        domain: c.domain,
        company: c.company,
        education: c.education,
        skillScore: c.skillScore,
        roleScore: c.roleScore,
        experienceScore: c.experienceScore,
        domainScore: c.domainScore,
        trajectoryScore: c.trajectoryScore,
        referralScore: c.referralScore,
        riskScore: c.riskScore,
        reasoning: c.reasoning,
        resumeText: `${c.name} is a ${c.role} with ${c.experience} years of experience at ${c.company}. Skills: ${c.skills.join(', ')}. Domain: ${c.domain}. Location: ${c.location}. Education: ${c.education}.`,
      },
    });
    count++;
  }
  
  console.log(`✅ Seeded ${count} candidates`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
